name: Esegui script Python e salva il file CSV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specifica la versione di Python desiderata

    - name: Install dependencies
      run: pip install csv  # Assicurati che la libreria csv sia installata

    - name: Run Python script
      run: python script.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output.csv
        git commit -m "Aggiungi file CSV generato da GitHub Action"
        git push
